hosts:
  genesis:
    api-url: "192.168.1.104:8006"
    target-node: "genesis"
    lxc:
      default:
        start-on-boot: false
        storage-backend: local-lvm
        template-backend: local
        default-gateway: "192.168.1.1"
        network-bridge: "vmbr0"
        network-interface: "eth0"
      machines:
        - name: "firstlxc"
          vmid: 112
          os-template: "debian-11-standard_11.7-1_amd64.tar.zst"
          ssh-public-keys:
            - "/Users/tskr/.ssh/id_rsa.pub"
            - "/Users/tskr/.ssh/genesis.pub"
          ip-address: "192.168.1.30/24"
          cpus: 4
          memory: 2048
          disk-size: 100
          swap-size: 20
          tags: "asdf;fdsa;fds"

        - name: "secondlxc"
          vmid: 112
          os-template: "debian-11-standard_11.7-1_amd64.tar.zst"
          ssh-public-keys:
            - "/Users/tskr/.ssh/id_rsa.pub"
            - "/Users/tskr/.ssh/genesis.pub"
          start-on-boot: false
          storage-backend: local-lvm
          template-backend: local
          default-gateway: "192.168.1.1"
          network-bridge: "vmbr0"
          network-interface: "eth0"
          ip-address: "192.168.1.13/24"
          cpus: 4
          memory: 2048
          disk-size: 100
          swap-size: 0
          tags: "asdf;fdsa;fds"
      vm:
        default:
          start-on-boot: false
          storage-backend: local-lvm
          template-backend: local
          default-gateway: "192.168.1.1"
          network-bridge: "vmbr0"
          network-interface: "eth0"
        machines:
          - name: "firstvm"
            vmid: 114
            iso: "ubuntu-24.04.1-live-server-amd64.iso"
            ssh-public-keys:
            - "/Users/tskr/.ssh/id_rsa.pub"
            - "/Users/tskr/.ssh/genesis.pub"
            cpus: 4
            memory: 2048
            disk-size: 100
            swap-size: 0
            tags: "asdf;fdsa;oooooooo"


  hyperbook:
    api-url: "192.168.1.100:8006"
    target-node: "hyperbook"
    lxc:
      default:
        start-on-boot: false
        storage-backend: local-lvm
        template-backend: local
        default-gateway: "192.168.1.1"
        network-bridge: "vmbr0"
        network-interface: "eth0"

      machines:
        - name: "firstlxc"
          vmid: 1122
          os-template: "debian-11-standard_11.7-1_amd64.tar.zst"
          ssh-public-keys:
            - "/Users/tskr/.ssh/id_rsa.pub"
            - "/Users/tskr/.ssh/genesis.pub"
          ip-address: "192.168.1.20/24"
          cpus: 4
          memory: 2048
          disk-size: 100
          swap-size: 20
          tags: "asdf;bbbbbbbb;fds"


        - name: "secondlxc"
          vmid: 1124
          os-template: "debian-11-standard_11.7-1_amd64.tar.zst"
          ssh-public-keys:
            - "/Users/tskr/.ssh/id_rsa.pub"
            - "/Users/tskr/.ssh/genesis.pub"
          ip-address: "192.168.1.21/24"
          cpus: 4
          memory: 2048
          disk-size: 100
          swap-size: 0
          tags: "asdf;kok;fds"

      vm:
        default:
          start-on-boot: false
          storage-backend: local-lvm
          template-backend: local
          default-gateway: "192.168.1.1"
          network-bridge: "vmbr0"
          network-interface: "eth0"
        machines:
          - name: "firstvm"
            vmid: 11443
            iso: "ubuntu-24.04.1-live-server-amd64.iso"
            ssh-public-keys:
              - "/Users/tskr/.ssh/id_rsa.pub"
              - "/Users/tskr/.ssh/genesis.pub"
            cpus: 4
            memory: 2048
            disk-size: 100
            swap-size: 0
            tags: "ffasdfqwer1111234;fdsa;fds"

